export type Language = 'en' | 'uk';

export const translations = {
  en: {
    sidebar: {
      newAnalysis: "New Analysis",
      myProjects: "My Projects", // Changed from history to myProjects
      currentProject: "Current Project", // Still relevant for export and potentially other current project actions
      upload: "Upload & Sources", // Renamed for TopNav
      transcript: "Transcription", // Renamed for TopNav
      affinity: "Affinity Map", // Renamed for TopNav
      insights: "Insights", // Renamed for TopNav
      summary: "Summary", // Renamed for TopNav
      export: "Export",
      history: "History", // Kept for history section if needed, but My Projects is now primary
      geminiPowered: "Gemini Powered",
      model: "Model: Pro & Flash"
    },
    topNav: { // New section for top navigation specific translations
      uploadSources: "Upload & Sources",
      transcript: "Transcription",
      affinity: "Affinity Map",
      insights: "Insights",
      summary: "Summary",
    },
    start: {
      title: "See insights",
      titleHighlight: "instantly",
      subtitle: "The AI Research Assistant that turns raw interviews into clarity.\nVideo, audio, or text — analyzed in seconds.",
      button: "Start Analysis",
      footer: "Powered by Google Gemini 2.5 Flash & 3 Pro"
    },
    upload: {
      title: "Import Research",
      subtitle: "Upload your interviews to begin decoding insights.",
      projectName: "Project Name",
      dragDrop: "Drag & drop your file",
      supports: "Supports Video (MP4), Audio (MP3/WAV), or Text (TXT).",
      maxSize: "Max 500MB",
      browse: "Browse Files",
      record: "Record Audio",
      stopRecord: "Stop Recording",
      secure: "Your files are processed securely and locally via API.",
      extracting: "Extracting audio...",
      uploading: "Uploading",
      wait: "Please wait while we securely upload your research file to Gemini.\nDo not close this tab.",
      uploadedFiles: "Uploaded Files",
      projectFiles: "Project Files"
    },
    processing: {
      title: "Analyzing Data",
      step1: "Processing file in cloud...",
      step2: "Transcribing audio with Gemini Flash...",
      step3: "Analyzing semantic patterns...",
      step4: "Extracting insights with Gemini Pro...",
      step5: "Synthesizing summary..."
    },
    success: {
      title: "Your analysis is ready ✨",
      subtitle: "ReserchOO has found key insights in your data.",
      button: "Go see the insights"
    },
    transcript: {
      title: "Transcript",
      autoTagged: "AI Auto-tagged",
      tags: "Tags",
      highlights: "Highlights",
      filtered: "Filtered",
      clear: "Clear",
      all: "ALL",
      noHighlights: "No highlights found for this filter.",
      noData: "No transcript data available."
    },
    affinity: {
      title: "Affinity Map",
      subtitle: "Clusters generated automatically by Gemini."
    },
    insights: {
      title: "Research Insights",
      subtitle: "Synthesized patterns and opportunities.",
      sentiment: "Overall Sentiment",
      distribution: "Sentiment Distribution",
      painPoints: "Pain Points",
      opportunities: "Opportunities",
      patterns: "Behavioral Patterns"
    },
    summary: {
      executive: "Executive Summary",
      generatedBy: "Generated by ReserchOO AI",
      overview: "Overview",
      keyFindings: "Key Findings",
      voice: "Voice of the User",
      tasks: "Actionable Tasks",
      sort: "Sort by Priority",
      highLow: "High → Low",
      lowHigh: "Low → High",
      priority: {
        High: "High",
        Medium: "Medium",
        Low: "Low"
      }
    },
    export: {
      title: "Export & Share",
      subtitle: "Your insights are ready to be moved to your workspace.",
      notion: "Export to Notion",
      notionSub: "Pages + Database",
      pdf: "Download PDF",
      pdfSub: "Executive Report",
      csv: "Export CSV",
      csvSub: "Raw Data & Tags",
      done: "All done! ✨",
      newProject: "Start New Project"
    },
    common: {
      error: "Upload Failed"
    }
  },
  uk: {
    sidebar: {
      newAnalysis: "Новий аналіз",
      myProjects: "Мої проекти", // Changed from history to myProjects
      currentProject: "Поточний проект",
      upload: "Завантаження та джерела",
      transcript: "Транскрипція",
      affinity: "Карта афініті",
      insights: "Інсайти",
      summary: "Підсумок",
      export: "Експорт",
      history: "Історія",
      geminiPowered: "На базі Gemini",
      model: "Модель: Pro & Flash"
    },
    topNav: { // New section for top navigation specific translations
      uploadSources: "Завантаження та джерела",
      transcript: "Транскрипція",
      affinity: "Карта афініті",
      insights: "Інсайти",
      summary: "Підсумок",
    },
    start: {
      title: "Бачте інсайти",
      titleHighlight: "миттєво",
      subtitle: "AI-асистент, який перетворює сирі інтерв'ю на чіткі висновки.\nВідео, аудіо або текст — аналіз за секунди.",
      button: "Почати аналіз",
      footer: "На базі Google Gemini 2.5 Flash & 3 Pro"
    },
    upload: {
      title: "Імпорт матеріалів",
      subtitle: "Завантажте інтерв'ю, щоб почати розшифровку інсайтів.",
      projectName: "Назва проекту",
      dragDrop: "Перетягніть файл сюди",
      supports: "Підтримує Відео (MP4), Аудіо (MP3/WAV) або Текст (TXT).",
      maxSize: "Макс 500МБ",
      browse: "Обрати файл",
      record: "Записати аудіо",
      stopRecord: "Зупинити запис",
      secure: "Ваші файли обробляються безпечно через API.",
      extracting: "Витягування аудіо...",
      uploading: "Завантаження",
      wait: "Будь ласка, зачекайте, поки ми безпечно завантажуємо ваш файл у Gemini.\nНе закривайте цю вкладку.",
      uploadedFiles: "Завантажені файли",
      projectFiles: "Файли проекту"
    },
    processing: {
      title: "Аналіз даних",
      step1: "Обробка файлу в хмарі...",
      step2: "Транскрибація аудіо через Gemini Flash...",
      step3: "Аналіз семантичних патернів...",
      step4: "Вилучення інсайтів через Gemini Pro...",
      step5: "Формування підсумків..."
    },
    success: {
      title: "Ваш аналіз готовий ✨",
      subtitle: "ReserchOO знайшов ключові інсайти у ваших даних.",
      button: "Переглянути інсайти"
    },
    transcript: {
      title: "Транскрипт",
      autoTagged: "AI авто-теги",
      tags: "Теги",
      highlights: "Хайлайти",
      filtered: "Фільтр",
      clear: "Очистити",
      all: "ВСІ",
      noHighlights: "Хайлайтів за цим фільтром не знайдено.",
      noData: "Дані транскрипції відсутні."
    },
    affinity: {
      title: "Карта афініті",
      subtitle: "Кластери, згенеровані автоматично за допомогою Gemini."
    },
    insights: {
      title: "Дослідницькі інсайти",
      subtitle: "Синтезовані патерни та можливості.",
      sentiment: "Загальний настрій",
      distribution: "Розподіл настроїв",
      painPoints: "Больові точки",
      opportunities: "Можливості",
      patterns: "Поведінкові патерни"
    },
    summary: {
      executive: "Виконавче резюме",
      generatedBy: "Згенеровано ReserchOO AI",
      overview: "Огляд",
      keyFindings: "Ключові знахідки",
      voice: "Голос користувача",
      tasks: "Задачі до виконання",
      sort: "Сортувати за пріоритетом",
      highLow: "Вис → Низ",
      lowHigh: "Низ → Вис",
      priority: {
        High: "Високий",
        Medium: "Середній",
        Low: "Низький"
      }
    },
    export: {
      title: "Експорт та Поширення",
      subtitle: "Ваші інсайти готові до перенесення у робочий простір.",
      notion: "Експорт в Notion",
      notionSub: "Сторінки + База даних",
      pdf: "Завантажити PDF",
      pdfSub: "Виконавчий звіт",
      csv: "Експорт CSV",
      csvSub: "Сирі дані та теги",
      done: "Все готово! ✨",
      newProject: "Почати новий проект"
    },
    common: {
      error: "Помилка завантаження"
    }
  }
};